---
title: "prelim data analysis"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Loading libraries
```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
library(skimr)
library(ggthemes)
library(naniar)
library(readr)
```

Loading colors
```{r}
colors <- paletteer::palettes_d_names
#view(colors)
```

Loading data
```{r}
weekly_size <- readxl::read_xlsx("data/cbs_drought_project.xlsx", sheet = "Weekly Surveys (complete racks)")
weekly_size
```

Cleaning data
```{r}
weekly_size_cleaned <- weekly_size %>% 
  pivot_longer(-c(pop, age, rep, treatment),
               names_to = "date",
               values_to = "measurement") %>% 
  separate(date, into = c("month", "day", "size measurement"),
           sep = "_") %>% 
  mutate_all(tolower) %>%
  janitor::clean_names()
weekly_size_cleaned
```

```{r}
weekly_size_cleaned$day <- as.numeric(weekly_size_cleaned$day)
weekly_size_cleaned$measurement <- as.numeric(weekly_size_cleaned$measurement)
weekly_size_cleaned$treatment <- as.factor(weekly_size_cleaned$treatment)
weekly_size_cleaned
```

```{r}
weekly_size_cleaned <- weekly_size_cleaned %>% 
  mutate(day = day - 9)
weekly_size_cleaned
```

```{r}
weekly_size_cleaned <- weekly_size_cleaned %>%
  mutate(elevation = case_when(pop == "sq1" | pop == "wl2" | pop == "yo1" | pop == "sq3" ~ "high",
                               pop == "dpr" | pop == "kc2" | pop == "wl1" ~ "intermediate",
                               pop == "tm2" | pop == "bh" | pop == "ih" ~ "low")) %>% 
  mutate(age = case_when(age == "a1" ~ "7wk",
                         age == "a2" ~ "5wk",
                         age == "a3" ~ "3wk")) %>% 
  select(-month)
glimpse(weekly_size_cleaned)
weekly_size_cleaned
```

Weekly Size Survey: Height

```{r}
summary(weekly_size_cleaned)
```


```{r}
weekly_size_cleaned %>% 
  filter(treatment == "severe drought", size_measurement == "height") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, color = elevation)) +
  geom_boxplot() +
  labs(x = "Population",
       y = "Height (cm)",
       color = "Elevation",
       title = "Height under Severe Drought Conditions") +
  ylim(0,8)
```
```{r}
weekly_size_cleaned %>% 
  filter(treatment == "light drought", size_measurement == "height") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, color = elevation)) +
  geom_boxplot() +
  labs(x = "Population",
       y = "Height (cm)",
       color = "Elevation",
       title = "Height under Light Drought Conditions") +
  ylim(0, 10)
```
```{r}
weekly_size_cleaned %>% 
  filter(treatment == "control", size_measurement == "height") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, color = elevation)) +
  geom_boxplot() +
  labs(x = "Population",
       y = "Height (cm)",
       color = "Elevation",
       title = "Height under Control Conditions") +
  ylim(0, 10)
```
```{r}
weekly_size_cleaned %>% 
  filter(size_measurement == "height") %>%
  filter(measurement != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, color = elevation, fill = treatment)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}
weekly_size_cleaned %>% 
  filter(size_measurement == "height") %>%
  filter(measurement != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  facet_wrap(~treatment)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  ylim(0, 10)
```


```{r}
weekly_size_cleaned %>% 
  filter(size_measurement == "height") %>%
  filter(pop != "NA") %>% 
  group_by(pop, treatment) %>% 
  summarise(mean_height = mean(measurement)) %>% 
  ggplot(aes(x = pop, y = mean_height, fill = pop)) +
  scale_fill_manual(values = paletteer::paletteer_d("LaCroixColoR::paired")) +
  geom_col(position = "dodge") +
  facet_wrap(~treatment) +
  labs(x = "pop",
       y = "height (cm)")
```

```{r}
weekly_size_cleaned %>% 
  filter(size_measurement == "height") %>%
  filter(pop != "NA") %>% 
  group_by(pop, treatment) %>% 
  summarise(mean_height = mean(measurement)) %>% 
  ggplot(aes(x = treatment, y = mean_height, color = pop)) +
  scale_color_manual(values = paletteer::paletteer_d("LaCroixColoR::paired")) +
  geom_point()+
  geom_line(aes(group = pop))+
  labs(x = "pop",
       y = "height (cm)")
```


```{r}
weekly_size_cleaned %>% 
  filter(size_measurement == "height") %>%
  filter(pop != "NA") %>% 
  group_by(pop, treatment, age, elevation) %>% 
  summarise(mean_height = mean(measurement)) %>% 
  ggplot(aes(x = age, y = mean_height, fill = elevation)) +
  scale_fill_manual(values = paletteer::paletteer_d("LaCroixColoR::paired")) +
  geom_col(position = "dodge") +
  facet_wrap(~pop) +
  labs(x = "pop",
       y = "height (cm)")
```

```{r}
weekly_size_cleaned %>% 
  filter(size_measurement == "height") %>%
  filter(pop != "NA") %>% 
  group_by(pop, treatment, age, elevation) %>% 
  summarise(mean_height = mean(measurement)) %>% 
  ggplot(aes(x = age, y = mean_height, fill = elevation)) +
  scale_fill_manual(values = paletteer::paletteer_d("LaCroixColoR::paired")) +
  geom_col(position = "dodge") +
  facet_wrap(~pop) +
  labs(x = "pop",
       y = "height (cm)")
```

```{r}
weekly_size_cleaned %>% 
  filter(treatment == "control", size_measurement == "height", age == "3wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}
weekly_size_cleaned %>% 
  filter(treatment == "control", size_measurement == "height", age == "5wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}
weekly_size_cleaned %>% 
  filter(treatment == "control", size_measurement == "height", age == "7wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}
weekly_size_cleaned %>% 
  filter(treatment == "light drought", size_measurement == "height", age == "7wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}
weekly_size_cleaned %>% 
  filter(treatment == "control", size_measurement == "height", age == "3wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```


```{r}
weekly_size_cleaned %>% 
  filter(treatment == "control", size_measurement == "height", age == "5wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}
weekly_size_cleaned %>% 
  filter(treatment == "control", size_measurement == "height", age == "7wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}
weekly_size_cleaned %>% 
  filter(treatment == "light drought", size_measurement == "height", age == "3wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}
weekly_size_cleaned %>% 
  filter(treatment == "light drought", size_measurement == "height", age == "5wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}
weekly_size_cleaned %>% 
  filter(treatment == "light drought", size_measurement == "height", age == "7wk") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = pop, y = measurement, fill = elevation)) +
  geom_boxplot() +
  labs(x = "pop",
       y = "height (cm)") +
  ylim(0, 10)
```


```{r}
weekly_size_cleaned %>% 
  filter(treatment == "control", size_measurement == "height") %>%
  filter(pop != "NA") %>% 
  ggplot(aes(x = age, y = measurement, fill = pop)) +
  geom_boxplot() +
  labs(x = "age",
       y = "height (cm)") +
  ylim(0, 10)
```

```{r}

```

